### ISSUE TITLE
502: Bad Gateway - other problem

### ISSUE THREAD

**Issue by pbaszyn** [arthurdent75/SimpleScheduler#109]
Hi, 

I installed first time buggy version two days ago. And I found same issues like others.
But now after update to newest version I still have this problem, but log's look's a little bit different.

[18:20:59] INFO: Running scheduler.sh
[2023-01-09 18:20:59] STATUS: Starting main program
Traceback (most recent call last):
  File "/simplescheduler/main.py", line 783, in <module>
    printlog('STATUS: Starting main program')
  File "/simplescheduler/main.py", line 749, in printlog
    with open(logfilepath, "a", encoding='utf-8') as logfile:
FileNotFoundError: [Errno 2] No such file or directory: '/share/simplescheduler/simplescheduler.log'
[2023-01-09 18:21:00] STATUS: Starting scheduler
Traceback (most recent call last):
  File "/simplescheduler/scheduler.py", line 13, in <module>
    main.printlog('STATUS: Starting scheduler')
  File "/simplescheduler/main.py", line 749, in printlog
    with open(logfilepath, "a", encoding='utf-8') as logfile:
FileNotFoundError: [Errno 2] No such file or directory: '/share/simplescheduler/simplescheduler.log'
[18:21:00] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
[18:21:00] INFO: Starting service.d [Interface]
[18:21:00] INFO: Running interface.sh
[18:21:00] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory

**Comment by arthurdent75** [comment]
Manually create an empty _simplescheduler.log_
Meanwhile, I will fix this ASAP

**Comment by pbaszyn** [comment]
I didn't delete anything.
My steps were...
Yesterday I installed Simple Scheduler for very first time. It doesn't work so I waited for new version.
Then I upgraded to last version I got this ( above) 
In meantime I tried to reinstall, uninstall/ install and Pi restart. No result. Everything I did via gui, no manual changes.

**Comment by pbaszyn** [comment]
I never used this before, so I don't have backup to restore.
Shouldn't be this fully recreated after uninstall, Pi restart and install again?

**Comment by arthurdent75** [comment]
> Shouldn't be this fully recreated after uninstall, Pi restart and install again?
Yes, it should 😅 

Try to update to the latest 2.0.49
I just added a couple of failsafe if the folder is missing.

Thank you for your precious feedback.

**Comment by pbaszyn** [comment]
Updated, and works !
Thanks man !

**Comment by TeleporterGuy** [comment]
2.0.50
I still keep getting 502: bad gateway error. Already updated from 2.0.45 through .47/49 to .50 version. Previously had 0.64 version with some scheduleres set up. Can I provide you with some data?

**Comment by arthurdent75** [comment]
@TeleporterGuy seems that the addon doesn't start.
Could you take a look at the log on the addon page?
Then take a look in the /share/simplescheduler/simplescheduler.log file under the samba share

**Comment by TeleporterGuy** [comment]
@arthurdent75 restarting the addon did not help, but i tried again reinstalling it and it is running now. Will come back, if the issue happens again. Thanks
