### ISSUE TITLE
Application crashes if you write the time with dot instead of colon

### ISSUE THREAD

**Issue by Manseiler** [arthurdent75/SimpleScheduler#177]
Hello
I was so happy with this integration,,, manaing maily cliamte and switches.. , so well done and simple

Since days I am not able to run..
Always never ending starting..., or crashing or whtever 
I already spent som mch time to solve (re-installing, new building etc..)
with 12.0 and 12.4  HA versions, all tried
but not solution found yet..
I am on the verge to make a handmade automations , which would be a pity..
Suppport more then welcome
Manfred
---------------------------
    if 0 <= int(hm[0]) < 24 and 0 <= int(hm[1]) < 60:
ValueError: invalid literal for int() with base 10: '23.00'
[07:54:01] WARNING: Scheduler process crashed...
[07:54:01] INFO: Restarting...
[07:54:01] INFO: Starting service.d [Scheduler]
[07:54:01] INFO: Running scheduler.sh
[2024-12-20 07:54:02] STATUS: Starting scheduler
Traceback (most recent call last):
  File "/simplescheduler/scheduler.py", line 95, in <module>
    event_time = main.evaluate_event_time(t, sunrise, sunset)
  File "/simplescheduler/main.py", line 823, in evaluate_event_time
    if 0 <= int(hm[0]) < 24 and 0 <= int(hm[1]) < 60:
ValueError: invalid literal for int() with base 10: '23.00'
[07:55:00] WARNING: Scheduler process crashed...
[07:55:00] INFO: Restarting...
[07:55:00] INFO: Starting service.d [Scheduler]
[07:55:00] INFO: Running scheduler.sh
[2024-12-20 07:55:01] STATUS: Starting scheduler
Traceback (most recent call last):
  File "/simplescheduler/scheduler.py", line 95, in <module>
    event_time = main.evaluate_event_time(t, sunrise, sunset)
  File "/simplescheduler/main.py", line 823, in evaluate_event_time
    if 0 <= int(hm[0]) < 24 and 0 <= int(hm[1]) < 60:

**Comment by Manseiler** [comment]
Thanks, what a shame (to me)  .. , I checked so much.., but I did not see this
But I had this : issue some times already , (then the single schedule did not work, but the rest was ok) but I do not remember such a never ending blocking...
Might be good to have a syntax check point, like you mentioned
Many thanks !!!!!!!!!!!!

**Comment by arthurdent75** [comment]
Fixed in v2.6
